config/routes.rb
Rails.application.routes.draw do
  resources :beams

  root 'bea_ms#index'

end

app/models/beams.rb
class Beams < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bea_ms_controller.rb
class BeaMsController < ApplicationController
  before_action :set_beam, only: [:show, :edit, :update, :destroy]

  # GET /beams
  # GET /beams.json
  def index
    @beams = Beams.all
  end

  # GET /beams/1
  # GET /beams/1.json
  def show
  end

  # GET /beams/new
  def new
    @beam = Beams.new
  end

  # GET /beams/1/edit
  def edit
  end

  # POST /beams
  # POST /beams.json
  def create
    @beam = Beams.new(beam_params)

    respond_to do |format|
      if @beam.save
        format.html { redirect_to @beam, notice: 'Beams was successfully created.' }
        format.json { render :show, status: :created, location: @beam }
      else
        format.html { render :new }
        format.json { render json: @beam.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beams/1
  # PATCH/PUT /beams/1.json
  def update
    respond_to do |format|
      if @beam.update(beam_params)
        format.html { redirect_to @beam, notice: 'Beams was successfully updated.' }
        format.json { render :show, status: :ok, location: @beam }
      else
        format.html { render :edit }
        format.json { render json: @beam.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beams/1
  # DELETE /beams/1.json
  def destroy
    @beam.destroy
    respond_to do |format|
      format.html { redirect_to beams_index_url, notice: 'Beams was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_beam
      @beam = Beams.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def beam_params
      params.fetch(:beam, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bea_ms_helper.rb
module BeaMsHelper
end

app/views/bea_ms/_form.html.erb
<%= form_for(@beam) do |f| %>
  <% if @beam.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@beam.errors.count, "error") %> prohibited this beam from being saved:</h2>

      <ul>
      <% @beam.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bea_ms/edit.html.erb
<h1>Editing Beam</h1>

<%= render 'form' %>

<%= link_to 'Show', @beam %> |
<%= link_to 'Back', beams_index_path %>

app/views/bea_ms/index.html.erb
require 'rubygems'
require 'nokogiri'
require 'open-uri'

url = 'http://shop.beams.co.jp/'

charset = nil
html = open(url) do |f|
 charset = f.charset # 文字種別を取得
 f.read # htmlを読み込んで変数htmlに渡す
end

# htmlをパース(解析)してオブジェクトを生成
doc = Nokogiri::HTML.parse(html, nil, charset)

doc.xpath('//li[@class="on"]').each do |node|
 # tilte
 p node.css('h3').inner_text

 # 記事のサムネイル画像
 p node.css('img').attribute('src').value

 # 記事のサムネイル画像
 p node.css('a').attribute('href').value
end

app/views/bea_ms/new.html.erb
<h1>New Beam</h1>

<%= render 'form' %>

<%= link_to 'Back', beams_index_path %>

app/views/bea_ms/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_beam_path(@beam) %> |
<%= link_to 'Back', beams_index_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>